const data = {
  props: {
    pageProps: {
      sites: {
        id: 1,
        attributes: {
          title: "Biopedia",
          createdAt: "2022-05-09T13:35:53.921Z",
          updatedAt: "2022-09-18T16:46:31.439Z",
          publishedAt: "2022-05-09T13:35:58.721Z",
          bottomText:
            "### Био – значение на думата\nС настъпването на XXI-и век човекът все повече започва да си прави сметка за това как се грижи за планетата и нейните изчерпаеми ресурси. В последните години все по-често се използва думата био и за това е важно да знаем какво ни показва тя. \n/n/n\nВсеки един био продукт, който закупите от магазина, трябва да покрие стриктни изисквания заложени от държавата със закон, за да стигне до потребителите. Това са продукти, които имат сертификати, удостоверяващи органичния им произход, както и начина на производство. \n\nСтандарти и етикиране на био продуктите\n\nЧесто био продукт се бърка с натурален продукт. Разликата между тях е голяма, а най-важно е уточнението, че за био продукт съществуват строги стандарти. Те включват производство, обработка, преработка и други. Тези стандарти важат за целия свят. За сравнение – при натуралните продукти такива стандарти липсват в по голямата част от света. \n\nОтносно етикетите – за тях също има изисквания. Всеки производител трябва да се съобрази с правила и регламенти преди да сложи знака „Био“ на своя продукт. \n\nВсе повече хора избират да ползват био продукти. Причината за това, е че поради строгия контрол, който се налага над тези продукти, хората могат да бъдат сигурни, че не са използвани вредни химикали. \n\nВ наши дни био продуктите са достъпни за всеки човек. Те се продават в специални магазини, а и в масовите супермаркети вече има специални секции за тези, които търсят био. \n\nБио храни\n\nБио храните са сред най-търсените продукти от категорията „био“. Човек все повече се опитва да се храни здравословно. Но какви са предимствата на Био храните?\n-\tНе се използват синтетични химически вещества като пестициди, хербициди и други.\n-\tНе се използват генни технологии. Под никаква форма.\n-\tСъдържат по-добри вкусови и хранителни вещества. Причина за това е, че са обработени по целесъобразен начин.\n-\tОтговарят на строги стандарти и нямат скрити разходи. ",
          categories: {
            data: [
              {
                id: 1,
                attributes: {
                  name: "Био здраве - biopedia",
                  slug: "bio-zdrave",
                  createdAt: "2022-05-09T13:36:09.559Z",
                  updatedAt: "2022-08-03T16:21:14.095Z",
                  publishedAt: "2022-05-09T13:37:23.567Z",
                  bottomText:
                    "### Био – значение на думата\nС настъпването на XXI-и век човекът все повече започва да си прави сметка за това как се грижи за планетата и нейните изчерпаеми ресурси. В последните години все по-често се използва думата био и за това е важно да знаем какво ни показва тя. \n/n/n\nВсеки един био продукт, който закупите от магазина, трябва да покрие стриктни изисквания заложени от държавата със закон, за да стигне до потребителите. Това са продукти, които имат сертификати, удостоверяващи органичния им произход, както и начина на производство. \n\nСтандарти и етикиране на био продуктите\n\nЧесто био продукт се бърка с натурален продукт. Разликата между тях е голяма, а най-важно е уточнението, че за био продукт съществуват строги стандарти. Те включват производство, обработка, преработка и други. Тези стандарти важат за целия свят. За сравнение – при натуралните продукти такива стандарти липсват в по голямата част от света. \n\nОтносно етикетите – за тях също има изисквания. Всеки производител трябва да се съобрази с правила и регламенти преди да сложи знака „Био“ на своя продукт. \n\nВсе повече хора избират да ползват био продукти. Причината за това, е че поради строгия контрол, който се налага над тези продукти, хората могат да бъдат сигурни, че не са използвани вредни химикали. \n\nВ наши дни био продуктите са достъпни за всеки човек. Те се продават в специални магазини, а и в масовите супермаркети вече има специални секции за тези, които търсят био. \n\nБио храни\n\nБио храните са сред най-търсените продукти от категорията „био“. Човек все повече се опитва да се храни здравословно. Но какви са предимствата на Био храните?\n-\tНе се използват синтетични химически вещества като пестициди, хербициди и други.\n-\tНе се използват генни технологии. Под никаква форма.\n-\tСъдържат по-добри вкусови и хранителни вещества. Причина за това е, че са обработени по целесъобразен начин.\n-\tОтговарят на строги стандарти и нямат скрити разходи. ",
                },
              },
              {
                id: 2,
                attributes: {
                  name: "Био каузи - biopedia",
                  slug: "bio-kauzi",
                  createdAt: "2022-05-10T06:54:48.558Z",
                  updatedAt: "2022-07-23T14:24:42.937Z",
                  publishedAt: "2022-05-10T06:54:49.744Z",
                  bottomText: null,
                },
              },
              {
                id: 3,
                attributes: {
                  name: "Био козметика - biopedia",
                  slug: "bio-kozmetika",
                  createdAt: "2022-05-13T10:57:54.106Z",
                  updatedAt: "2022-07-23T14:24:48.193Z",
                  publishedAt: "2022-05-13T10:58:03.406Z",
                  bottomText: null,
                },
              },
              {
                id: 4,
                attributes: {
                  name: "Био продукти - biopedia",
                  slug: "bio-produkti",
                  createdAt: "2022-05-13T10:58:48.140Z",
                  updatedAt: "2022-07-23T14:24:53.496Z",
                  publishedAt: "2022-05-13T10:58:48.970Z",
                  bottomText: null,
                },
              },
              {
                id: 5,
                attributes: {
                  name: "Био рецепти - biopedia",
                  slug: "bio-recepti",
                  createdAt: "2022-05-13T10:59:13.314Z",
                  updatedAt: "2022-07-23T14:25:05.212Z",
                  publishedAt: "2022-05-13T10:59:13.982Z",
                  bottomText: null,
                },
              },
              {
                id: 6,
                attributes: {
                  name: "Био храни - biopedia",
                  slug: "bio-hrani",
                  createdAt: "2022-05-13T10:59:35.098Z",
                  updatedAt: "2022-07-23T14:25:10.806Z",
                  publishedAt: "2022-05-13T10:59:35.818Z",
                  bottomText: null,
                },
              },
            ],
          },
          seo: {
            id: 1,
            metaTitle: "Био храни, Био рецепти, Био продукти",
            metaDescription:
              "Biopedia.bg предлага разновидности за вашия здравословен начин на живот. Био продукти, Био храни и всичко необходимо ще откриете при нас.",
          },
          defaultSeo: {
            id: 2,
            metaTitle: "Вашата енциклопедия в света на БИО индустрията.",
            metaDescription: "Вашата енциклопедия в света на БИО индустрията.",
          },
        },
      },
      articles: {
        data: [
          {
            id: 755,
            attributes: {
              createdAt: "2022-11-21T14:42:45.153Z",
              title:
                "4 ползи за здравето от салвията и как можете да я използвате у дома",
              description:
                "прочете статията за да разберете кои са четирите ползи за здравето от салвията и как можете да я използвате у дома.",
              slug: "4-polzi-za-zdraveto-ot-salviyata-i-kak-mozhete-da-ya-izpolzvate-u-doma",
              exclusive: null,
              image: {
                data: {
                  id: 3310,
                  attributes: {
                    name: "70.jpg",
                    alternativeText: "70.jpg",
                    caption: "70.jpg",
                    width: 912,
                    height: 513,
                    formats: {
                      small: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669042712/small_70_347e0adfa3.jpg",
                        hash: "small_70_347e0adfa3",
                        mime: "image/jpeg",
                        name: "small_70.jpg",
                        path: null,
                        size: 31.83,
                        width: 500,
                        height: 281,
                        provider_metadata: {
                          public_id: "small_70_347e0adfa3",
                          resource_type: "image",
                        },
                      },
                      medium: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669042711/medium_70_347e0adfa3.jpg",
                        hash: "medium_70_347e0adfa3",
                        mime: "image/jpeg",
                        name: "medium_70.jpg",
                        path: null,
                        size: 63.03,
                        width: 750,
                        height: 422,
                        provider_metadata: {
                          public_id: "medium_70_347e0adfa3",
                          resource_type: "image",
                        },
                      },
                      thumbnail: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669042710/thumbnail_70_347e0adfa3.jpg",
                        hash: "thumbnail_70_347e0adfa3",
                        mime: "image/jpeg",
                        name: "thumbnail_70.jpg",
                        path: null,
                        size: 9.39,
                        width: 245,
                        height: 138,
                        provider_metadata: {
                          public_id: "thumbnail_70_347e0adfa3",
                          resource_type: "image",
                        },
                      },
                    },
                    hash: "70_347e0adfa3",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    size: 87.66,
                    url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669042709/70_347e0adfa3.jpg",
                    previewUrl: null,
                    provider: "cloudinary",
                    provider_metadata: {
                      public_id: "70_347e0adfa3",
                      resource_type: "image",
                    },
                    createdAt: "2022-11-21T14:58:32.549Z",
                    updatedAt: "2022-11-21T14:58:32.549Z",
                  },
                },
              },
              categories: {
                data: [
                  {
                    id: 1,
                    attributes: {
                      name: "Био здраве - biopedia",
                      slug: "bio-zdrave",
                      createdAt: "2022-05-09T13:36:09.559Z",
                      updatedAt: "2022-08-03T16:21:14.095Z",
                      publishedAt: "2022-05-09T13:37:23.567Z",
                      bottomText:
                        "### Био – значение на думата\nС настъпването на XXI-и век човекът все повече започва да си прави сметка за това как се грижи за планетата и нейните изчерпаеми ресурси. В последните години все по-често се използва думата био и за това е важно да знаем какво ни показва тя. \n/n/n\nВсеки един био продукт, който закупите от магазина, трябва да покрие стриктни изисквания заложени от държавата със закон, за да стигне до потребителите. Това са продукти, които имат сертификати, удостоверяващи органичния им произход, както и начина на производство. \n\nСтандарти и етикиране на био продуктите\n\nЧесто био продукт се бърка с натурален продукт. Разликата между тях е голяма, а най-важно е уточнението, че за био продукт съществуват строги стандарти. Те включват производство, обработка, преработка и други. Тези стандарти важат за целия свят. За сравнение – при натуралните продукти такива стандарти липсват в по голямата част от света. \n\nОтносно етикетите – за тях също има изисквания. Всеки производител трябва да се съобрази с правила и регламенти преди да сложи знака „Био“ на своя продукт. \n\nВсе повече хора избират да ползват био продукти. Причината за това, е че поради строгия контрол, който се налага над тези продукти, хората могат да бъдат сигурни, че не са използвани вредни химикали. \n\nВ наши дни био продуктите са достъпни за всеки човек. Те се продават в специални магазини, а и в масовите супермаркети вече има специални секции за тези, които търсят био. \n\nБио храни\n\nБио храните са сред най-търсените продукти от категорията „био“. Човек все повече се опитва да се храни здравословно. Но какви са предимствата на Био храните?\n-\tНе се използват синтетични химически вещества като пестициди, хербициди и други.\n-\tНе се използват генни технологии. Под никаква форма.\n-\tСъдържат по-добри вкусови и хранителни вещества. Причина за това е, че са обработени по целесъобразен начин.\n-\tОтговарят на строги стандарти и нямат скрити разходи. ",
                    },
                  },
                ],
              },
            },
          },
          {
            id: 751,
            attributes: {
              createdAt: "2022-11-21T10:39:29.285Z",
              title: "Омега 3 – ползи и вреди върху нашето здраве",
              description: "Прочетете повече за Омега 3 тук",
              slug: "omega-3-polzi-i-vredi-vrhu-nasheto-zdrave",
              exclusive: null,
              image: {
                data: {
                  id: 3278,
                  attributes: {
                    name: "69.jpg",
                    alternativeText: "69.jpg",
                    caption: "69.jpg",
                    width: 912,
                    height: 513,
                    formats: {
                      small: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669027002/small_69_d60eca57c9.jpg",
                        hash: "small_69_d60eca57c9",
                        mime: "image/jpeg",
                        name: "small_69.jpg",
                        path: null,
                        size: 41.83,
                        width: 500,
                        height: 281,
                        provider_metadata: {
                          public_id: "small_69_d60eca57c9",
                          resource_type: "image",
                        },
                      },
                      medium: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669027001/medium_69_d60eca57c9.jpg",
                        hash: "medium_69_d60eca57c9",
                        mime: "image/jpeg",
                        name: "medium_69.jpg",
                        path: null,
                        size: 82.66,
                        width: 750,
                        height: 422,
                        provider_metadata: {
                          public_id: "medium_69_d60eca57c9",
                          resource_type: "image",
                        },
                      },
                      thumbnail: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669027000/thumbnail_69_d60eca57c9.jpg",
                        hash: "thumbnail_69_d60eca57c9",
                        mime: "image/jpeg",
                        name: "thumbnail_69.jpg",
                        path: null,
                        size: 11.8,
                        width: 245,
                        height: 138,
                        provider_metadata: {
                          public_id: "thumbnail_69_d60eca57c9",
                          resource_type: "image",
                        },
                      },
                    },
                    hash: "69_d60eca57c9",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    size: 116.51,
                    url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669027000/69_d60eca57c9.jpg",
                    previewUrl: null,
                    provider: "cloudinary",
                    provider_metadata: {
                      public_id: "69_d60eca57c9",
                      resource_type: "image",
                    },
                    createdAt: "2022-11-21T10:36:42.498Z",
                    updatedAt: "2022-11-21T10:36:42.498Z",
                  },
                },
              },
              categories: {
                data: [
                  {
                    id: 1,
                    attributes: {
                      name: "Био здраве - biopedia",
                      slug: "bio-zdrave",
                      createdAt: "2022-05-09T13:36:09.559Z",
                      updatedAt: "2022-08-03T16:21:14.095Z",
                      publishedAt: "2022-05-09T13:37:23.567Z",
                      bottomText:
                        "### Био – значение на думата\nС настъпването на XXI-и век човекът все повече започва да си прави сметка за това как се грижи за планетата и нейните изчерпаеми ресурси. В последните години все по-често се използва думата био и за това е важно да знаем какво ни показва тя. \n/n/n\nВсеки един био продукт, който закупите от магазина, трябва да покрие стриктни изисквания заложени от държавата със закон, за да стигне до потребителите. Това са продукти, които имат сертификати, удостоверяващи органичния им произход, както и начина на производство. \n\nСтандарти и етикиране на био продуктите\n\nЧесто био продукт се бърка с натурален продукт. Разликата между тях е голяма, а най-важно е уточнението, че за био продукт съществуват строги стандарти. Те включват производство, обработка, преработка и други. Тези стандарти важат за целия свят. За сравнение – при натуралните продукти такива стандарти липсват в по голямата част от света. \n\nОтносно етикетите – за тях също има изисквания. Всеки производител трябва да се съобрази с правила и регламенти преди да сложи знака „Био“ на своя продукт. \n\nВсе повече хора избират да ползват био продукти. Причината за това, е че поради строгия контрол, който се налага над тези продукти, хората могат да бъдат сигурни, че не са използвани вредни химикали. \n\nВ наши дни био продуктите са достъпни за всеки човек. Те се продават в специални магазини, а и в масовите супермаркети вече има специални секции за тези, които търсят био. \n\nБио храни\n\nБио храните са сред най-търсените продукти от категорията „био“. Човек все повече се опитва да се храни здравословно. Но какви са предимствата на Био храните?\n-\tНе се използват синтетични химически вещества като пестициди, хербициди и други.\n-\tНе се използват генни технологии. Под никаква форма.\n-\tСъдържат по-добри вкусови и хранителни вещества. Причина за това е, че са обработени по целесъобразен начин.\n-\tОтговарят на строги стандарти и нямат скрити разходи. ",
                    },
                  },
                  {
                    id: 4,
                    attributes: {
                      name: "Био продукти - biopedia",
                      slug: "bio-produkti",
                      createdAt: "2022-05-13T10:58:48.140Z",
                      updatedAt: "2022-07-23T14:24:53.496Z",
                      publishedAt: "2022-05-13T10:58:48.970Z",
                      bottomText: null,
                    },
                  },
                ],
              },
            },
          },
          {
            id: 750,
            attributes: {
              createdAt: "2022-11-21T10:23:09.861Z",
              title: "6 ползи от употребата на магнезиево олио",
              description: "Научете за всичко приложения на магнезиевото олио",
              slug: "6-polzi-ot-upotrebata-na-magnezievo-olio",
              exclusive: null,
              image: {
                data: {
                  id: 3273,
                  attributes: {
                    name: "68.jpg",
                    alternativeText: "68.jpg",
                    caption: "68.jpg",
                    width: 912,
                    height: 513,
                    formats: {
                      small: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669025935/small_68_f86c1973b0.jpg",
                        hash: "small_68_f86c1973b0",
                        mime: "image/jpeg",
                        name: "small_68.jpg",
                        path: null,
                        size: 20.68,
                        width: 500,
                        height: 281,
                        provider_metadata: {
                          public_id: "small_68_f86c1973b0",
                          resource_type: "image",
                        },
                      },
                      medium: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669025934/medium_68_f86c1973b0.jpg",
                        hash: "medium_68_f86c1973b0",
                        mime: "image/jpeg",
                        name: "medium_68.jpg",
                        path: null,
                        size: 36.43,
                        width: 750,
                        height: 422,
                        provider_metadata: {
                          public_id: "medium_68_f86c1973b0",
                          resource_type: "image",
                        },
                      },
                      thumbnail: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669025934/thumbnail_68_f86c1973b0.jpg",
                        hash: "thumbnail_68_f86c1973b0",
                        mime: "image/jpeg",
                        name: "thumbnail_68.jpg",
                        path: null,
                        size: 7.34,
                        width: 245,
                        height: 138,
                        provider_metadata: {
                          public_id: "thumbnail_68_f86c1973b0",
                          resource_type: "image",
                        },
                      },
                    },
                    hash: "68_f86c1973b0",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    size: 48.72,
                    url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669025933/68_f86c1973b0.jpg",
                    previewUrl: null,
                    provider: "cloudinary",
                    provider_metadata: {
                      public_id: "68_f86c1973b0",
                      resource_type: "image",
                    },
                    createdAt: "2022-11-21T10:18:55.998Z",
                    updatedAt: "2022-11-21T10:18:55.998Z",
                  },
                },
              },
              categories: {
                data: [
                  {
                    id: 4,
                    attributes: {
                      name: "Био продукти - biopedia",
                      slug: "bio-produkti",
                      createdAt: "2022-05-13T10:58:48.140Z",
                      updatedAt: "2022-07-23T14:24:53.496Z",
                      publishedAt: "2022-05-13T10:58:48.970Z",
                      bottomText: null,
                    },
                  },
                  {
                    id: 6,
                    attributes: {
                      name: "Био храни - biopedia",
                      slug: "bio-hrani",
                      createdAt: "2022-05-13T10:59:35.098Z",
                      updatedAt: "2022-07-23T14:25:10.806Z",
                      publishedAt: "2022-05-13T10:59:35.818Z",
                      bottomText: null,
                    },
                  },
                ],
              },
            },
          },
          {
            id: 749,
            attributes: {
              createdAt: "2022-11-21T10:18:53.555Z",
              title:
                "Витамини против косопад, които ще направят косата Ви здрава и блестяща",
              description:
                "Прочетете кои са витамините против косопад които ще накарат косата ви да блести.",
              slug: "vitamini-protiv-kosopad-koito-shhe-napravyat-kosata-vi-zdrava-i-blestyashha",
              exclusive: null,
              image: {
                data: {
                  id: 3282,
                  attributes: {
                    name: "66.jpg",
                    alternativeText: "66.jpg",
                    caption: "66.jpg",
                    width: 912,
                    height: 513,
                    formats: {
                      small: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669027211/small_66_51446c70a5.jpg",
                        hash: "small_66_51446c70a5",
                        mime: "image/jpeg",
                        name: "small_66.jpg",
                        path: null,
                        size: 39.01,
                        width: 500,
                        height: 281,
                        provider_metadata: {
                          public_id: "small_66_51446c70a5",
                          resource_type: "image",
                        },
                      },
                      medium: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669027210/medium_66_51446c70a5.jpg",
                        hash: "medium_66_51446c70a5",
                        mime: "image/jpeg",
                        name: "medium_66.jpg",
                        path: null,
                        size: 74.45,
                        width: 750,
                        height: 422,
                        provider_metadata: {
                          public_id: "medium_66_51446c70a5",
                          resource_type: "image",
                        },
                      },
                      thumbnail: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669027210/thumbnail_66_51446c70a5.jpg",
                        hash: "thumbnail_66_51446c70a5",
                        mime: "image/jpeg",
                        name: "thumbnail_66.jpg",
                        path: null,
                        size: 12.1,
                        width: 245,
                        height: 138,
                        provider_metadata: {
                          public_id: "thumbnail_66_51446c70a5",
                          resource_type: "image",
                        },
                      },
                    },
                    hash: "66_51446c70a5",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    size: 102.87,
                    url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669027209/66_51446c70a5.jpg",
                    previewUrl: null,
                    provider: "cloudinary",
                    provider_metadata: {
                      public_id: "66_51446c70a5",
                      resource_type: "image",
                    },
                    createdAt: "2022-11-21T10:40:12.022Z",
                    updatedAt: "2022-11-21T10:40:12.022Z",
                  },
                },
              },
              categories: {
                data: [
                  {
                    id: 1,
                    attributes: {
                      name: "Био здраве - biopedia",
                      slug: "bio-zdrave",
                      createdAt: "2022-05-09T13:36:09.559Z",
                      updatedAt: "2022-08-03T16:21:14.095Z",
                      publishedAt: "2022-05-09T13:37:23.567Z",
                      bottomText:
                        "### Био – значение на думата\nС настъпването на XXI-и век човекът все повече започва да си прави сметка за това как се грижи за планетата и нейните изчерпаеми ресурси. В последните години все по-често се използва думата био и за това е важно да знаем какво ни показва тя. \n/n/n\nВсеки един био продукт, който закупите от магазина, трябва да покрие стриктни изисквания заложени от държавата със закон, за да стигне до потребителите. Това са продукти, които имат сертификати, удостоверяващи органичния им произход, както и начина на производство. \n\nСтандарти и етикиране на био продуктите\n\nЧесто био продукт се бърка с натурален продукт. Разликата между тях е голяма, а най-важно е уточнението, че за био продукт съществуват строги стандарти. Те включват производство, обработка, преработка и други. Тези стандарти важат за целия свят. За сравнение – при натуралните продукти такива стандарти липсват в по голямата част от света. \n\nОтносно етикетите – за тях също има изисквания. Всеки производител трябва да се съобрази с правила и регламенти преди да сложи знака „Био“ на своя продукт. \n\nВсе повече хора избират да ползват био продукти. Причината за това, е че поради строгия контрол, който се налага над тези продукти, хората могат да бъдат сигурни, че не са използвани вредни химикали. \n\nВ наши дни био продуктите са достъпни за всеки човек. Те се продават в специални магазини, а и в масовите супермаркети вече има специални секции за тези, които търсят био. \n\nБио храни\n\nБио храните са сред най-търсените продукти от категорията „био“. Човек все повече се опитва да се храни здравословно. Но какви са предимствата на Био храните?\n-\tНе се използват синтетични химически вещества като пестициди, хербициди и други.\n-\tНе се използват генни технологии. Под никаква форма.\n-\tСъдържат по-добри вкусови и хранителни вещества. Причина за това е, че са обработени по целесъобразен начин.\n-\tОтговарят на строги стандарти и нямат скрити разходи. ",
                    },
                  },
                ],
              },
            },
          },
          {
            id: 748,
            attributes: {
              createdAt: "2022-11-21T10:01:58.188Z",
              title:
                "Куркума: 6 невероятни ползи за здравето, които вероятно не знаете",
              description:
                "Куркума, билката за която трябва да разберете повече.",
              slug: "kurkuma-6-neveroyatni-polzi-za-zdraveto-koito-veroyatno-ne-znaete",
              exclusive: null,
              image: {
                data: {
                  id: 3266,
                  attributes: {
                    name: "67.jpg",
                    alternativeText: "67.jpg",
                    caption: "67.jpg",
                    width: 912,
                    height: 513,
                    formats: {
                      small: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669024783/small_67_6acc0b2e7e.jpg",
                        hash: "small_67_6acc0b2e7e",
                        mime: "image/jpeg",
                        name: "small_67.jpg",
                        path: null,
                        size: 35.53,
                        width: 500,
                        height: 281,
                        provider_metadata: {
                          public_id: "small_67_6acc0b2e7e",
                          resource_type: "image",
                        },
                      },
                      medium: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669024782/medium_67_6acc0b2e7e.jpg",
                        hash: "medium_67_6acc0b2e7e",
                        mime: "image/jpeg",
                        name: "medium_67.jpg",
                        path: null,
                        size: 71.1,
                        width: 750,
                        height: 422,
                        provider_metadata: {
                          public_id: "medium_67_6acc0b2e7e",
                          resource_type: "image",
                        },
                      },
                      thumbnail: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669024781/thumbnail_67_6acc0b2e7e.jpg",
                        hash: "thumbnail_67_6acc0b2e7e",
                        mime: "image/jpeg",
                        name: "thumbnail_67.jpg",
                        path: null,
                        size: 10.59,
                        width: 245,
                        height: 138,
                        provider_metadata: {
                          public_id: "thumbnail_67_6acc0b2e7e",
                          resource_type: "image",
                        },
                      },
                    },
                    hash: "67_6acc0b2e7e",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    size: 104.61,
                    url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669024781/67_6acc0b2e7e.jpg",
                    previewUrl: null,
                    provider: "cloudinary",
                    provider_metadata: {
                      public_id: "67_6acc0b2e7e",
                      resource_type: "image",
                    },
                    createdAt: "2022-11-21T09:59:44.055Z",
                    updatedAt: "2022-11-21T09:59:44.055Z",
                  },
                },
              },
              categories: {
                data: [
                  {
                    id: 1,
                    attributes: {
                      name: "Био здраве - biopedia",
                      slug: "bio-zdrave",
                      createdAt: "2022-05-09T13:36:09.559Z",
                      updatedAt: "2022-08-03T16:21:14.095Z",
                      publishedAt: "2022-05-09T13:37:23.567Z",
                      bottomText:
                        "### Био – значение на думата\nС настъпването на XXI-и век човекът все повече започва да си прави сметка за това как се грижи за планетата и нейните изчерпаеми ресурси. В последните години все по-често се използва думата био и за това е важно да знаем какво ни показва тя. \n/n/n\nВсеки един био продукт, който закупите от магазина, трябва да покрие стриктни изисквания заложени от държавата със закон, за да стигне до потребителите. Това са продукти, които имат сертификати, удостоверяващи органичния им произход, както и начина на производство. \n\nСтандарти и етикиране на био продуктите\n\nЧесто био продукт се бърка с натурален продукт. Разликата между тях е голяма, а най-важно е уточнението, че за био продукт съществуват строги стандарти. Те включват производство, обработка, преработка и други. Тези стандарти важат за целия свят. За сравнение – при натуралните продукти такива стандарти липсват в по голямата част от света. \n\nОтносно етикетите – за тях също има изисквания. Всеки производител трябва да се съобрази с правила и регламенти преди да сложи знака „Био“ на своя продукт. \n\nВсе повече хора избират да ползват био продукти. Причината за това, е че поради строгия контрол, който се налага над тези продукти, хората могат да бъдат сигурни, че не са използвани вредни химикали. \n\nВ наши дни био продуктите са достъпни за всеки човек. Те се продават в специални магазини, а и в масовите супермаркети вече има специални секции за тези, които търсят био. \n\nБио храни\n\nБио храните са сред най-търсените продукти от категорията „био“. Човек все повече се опитва да се храни здравословно. Но какви са предимствата на Био храните?\n-\tНе се използват синтетични химически вещества като пестициди, хербициди и други.\n-\tНе се използват генни технологии. Под никаква форма.\n-\tСъдържат по-добри вкусови и хранителни вещества. Причина за това е, че са обработени по целесъобразен начин.\n-\tОтговарят на строги стандарти и нямат скрити разходи. ",
                    },
                  },
                  {
                    id: 4,
                    attributes: {
                      name: "Био продукти - biopedia",
                      slug: "bio-produkti",
                      createdAt: "2022-05-13T10:58:48.140Z",
                      updatedAt: "2022-07-23T14:24:53.496Z",
                      publishedAt: "2022-05-13T10:58:48.970Z",
                      bottomText: null,
                    },
                  },
                ],
              },
            },
          },
          {
            id: 747,
            attributes: {
              createdAt: "2022-11-21T09:39:05.022Z",
              title: "Бял равнец: всичко, което трябва да знаете",
              description:
                "Бял равнец, билката за която трябва да научите повече",
              slug: "byal-ravnecz-vsichko-koeto-tryabva-da-znaete",
              exclusive: null,
              image: {
                data: {
                  id: 3257,
                  attributes: {
                    name: "65.jpg",
                    alternativeText: "65.jpg",
                    caption: "65.jpg",
                    width: 912,
                    height: 513,
                    formats: {
                      small: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669023324/small_65_77696ceb13.jpg",
                        hash: "small_65_77696ceb13",
                        mime: "image/jpeg",
                        name: "small_65.jpg",
                        path: null,
                        size: 30.54,
                        width: 500,
                        height: 281,
                        provider_metadata: {
                          public_id: "small_65_77696ceb13",
                          resource_type: "image",
                        },
                      },
                      medium: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669023323/medium_65_77696ceb13.jpg",
                        hash: "medium_65_77696ceb13",
                        mime: "image/jpeg",
                        name: "medium_65.jpg",
                        path: null,
                        size: 56.17,
                        width: 750,
                        height: 422,
                        provider_metadata: {
                          public_id: "medium_65_77696ceb13",
                          resource_type: "image",
                        },
                      },
                      thumbnail: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669023322/thumbnail_65_77696ceb13.jpg",
                        hash: "thumbnail_65_77696ceb13",
                        mime: "image/jpeg",
                        name: "thumbnail_65.jpg",
                        path: null,
                        size: 9.41,
                        width: 245,
                        height: 138,
                        provider_metadata: {
                          public_id: "thumbnail_65_77696ceb13",
                          resource_type: "image",
                        },
                      },
                    },
                    hash: "65_77696ceb13",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    size: 74.44,
                    url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669023322/65_77696ceb13.jpg",
                    previewUrl: null,
                    provider: "cloudinary",
                    provider_metadata: {
                      public_id: "65_77696ceb13",
                      resource_type: "image",
                    },
                    createdAt: "2022-11-21T09:35:24.601Z",
                    updatedAt: "2022-11-21T09:35:24.601Z",
                  },
                },
              },
              categories: {
                data: [
                  {
                    id: 1,
                    attributes: {
                      name: "Био здраве - biopedia",
                      slug: "bio-zdrave",
                      createdAt: "2022-05-09T13:36:09.559Z",
                      updatedAt: "2022-08-03T16:21:14.095Z",
                      publishedAt: "2022-05-09T13:37:23.567Z",
                      bottomText:
                        "### Био – значение на думата\nС настъпването на XXI-и век човекът все повече започва да си прави сметка за това как се грижи за планетата и нейните изчерпаеми ресурси. В последните години все по-често се използва думата био и за това е важно да знаем какво ни показва тя. \n/n/n\nВсеки един био продукт, който закупите от магазина, трябва да покрие стриктни изисквания заложени от държавата със закон, за да стигне до потребителите. Това са продукти, които имат сертификати, удостоверяващи органичния им произход, както и начина на производство. \n\nСтандарти и етикиране на био продуктите\n\nЧесто био продукт се бърка с натурален продукт. Разликата между тях е голяма, а най-важно е уточнението, че за био продукт съществуват строги стандарти. Те включват производство, обработка, преработка и други. Тези стандарти важат за целия свят. За сравнение – при натуралните продукти такива стандарти липсват в по голямата част от света. \n\nОтносно етикетите – за тях също има изисквания. Всеки производител трябва да се съобрази с правила и регламенти преди да сложи знака „Био“ на своя продукт. \n\nВсе повече хора избират да ползват био продукти. Причината за това, е че поради строгия контрол, който се налага над тези продукти, хората могат да бъдат сигурни, че не са използвани вредни химикали. \n\nВ наши дни био продуктите са достъпни за всеки човек. Те се продават в специални магазини, а и в масовите супермаркети вече има специални секции за тези, които търсят био. \n\nБио храни\n\nБио храните са сред най-търсените продукти от категорията „био“. Човек все повече се опитва да се храни здравословно. Но какви са предимствата на Био храните?\n-\tНе се използват синтетични химически вещества като пестициди, хербициди и други.\n-\tНе се използват генни технологии. Под никаква форма.\n-\tСъдържат по-добри вкусови и хранителни вещества. Причина за това е, че са обработени по целесъобразен начин.\n-\tОтговарят на строги стандарти и нямат скрити разходи. ",
                    },
                  },
                  {
                    id: 6,
                    attributes: {
                      name: "Био храни - biopedia",
                      slug: "bio-hrani",
                      createdAt: "2022-05-13T10:59:35.098Z",
                      updatedAt: "2022-07-23T14:25:10.806Z",
                      publishedAt: "2022-05-13T10:59:35.818Z",
                      bottomText: null,
                    },
                  },
                ],
              },
            },
          },
          {
            id: 746,
            attributes: {
              createdAt: "2022-11-21T09:25:08.638Z",
              title: "Био мед",
              description:
                "За да разберете повече за био медът, прочетете тами статия.",
              slug: "bio-med",
              exclusive: null,
              image: {
                data: {
                  id: 3269,
                  attributes: {
                    name: "63.jpg",
                    alternativeText: "63.jpg",
                    caption: "63.jpg",
                    width: 912,
                    height: 513,
                    formats: {
                      small: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669025008/small_63_05e590896d.jpg",
                        hash: "small_63_05e590896d",
                        mime: "image/jpeg",
                        name: "small_63.jpg",
                        path: null,
                        size: 21.99,
                        width: 500,
                        height: 281,
                        provider_metadata: {
                          public_id: "small_63_05e590896d",
                          resource_type: "image",
                        },
                      },
                      medium: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669025007/medium_63_05e590896d.jpg",
                        hash: "medium_63_05e590896d",
                        mime: "image/jpeg",
                        name: "medium_63.jpg",
                        path: null,
                        size: 41.26,
                        width: 750,
                        height: 422,
                        provider_metadata: {
                          public_id: "medium_63_05e590896d",
                          resource_type: "image",
                        },
                      },
                      thumbnail: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669025006/thumbnail_63_05e590896d.jpg",
                        hash: "thumbnail_63_05e590896d",
                        mime: "image/jpeg",
                        name: "thumbnail_63.jpg",
                        path: null,
                        size: 7.26,
                        width: 245,
                        height: 138,
                        provider_metadata: {
                          public_id: "thumbnail_63_05e590896d",
                          resource_type: "image",
                        },
                      },
                    },
                    hash: "63_05e590896d",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    size: 56.55,
                    url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669025005/63_05e590896d.jpg",
                    previewUrl: null,
                    provider: "cloudinary",
                    provider_metadata: {
                      public_id: "63_05e590896d",
                      resource_type: "image",
                    },
                    createdAt: "2022-11-21T10:03:28.814Z",
                    updatedAt: "2022-11-21T10:03:28.814Z",
                  },
                },
              },
              categories: {
                data: [
                  {
                    id: 6,
                    attributes: {
                      name: "Био храни - biopedia",
                      slug: "bio-hrani",
                      createdAt: "2022-05-13T10:59:35.098Z",
                      updatedAt: "2022-07-23T14:25:10.806Z",
                      publishedAt: "2022-05-13T10:59:35.818Z",
                      bottomText: null,
                    },
                  },
                ],
              },
            },
          },
          {
            id: 745,
            attributes: {
              createdAt: "2022-11-21T09:00:14.395Z",
              title: "Бразилски орех: всичко, което трябва да знаете",
              description:
                "Прпочетете всичко за бразилския орех и неговите действия.",
              slug: "brazilski-oreh-vsichko-koeto-tryabva-da-znaete",
              exclusive: null,
              image: {
                data: {
                  id: 3246,
                  attributes: {
                    name: "64.jpg",
                    alternativeText: "64.jpg",
                    caption: "64.jpg",
                    width: 912,
                    height: 513,
                    formats: {
                      small: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669020500/small_64_d25fe38464.jpg",
                        hash: "small_64_d25fe38464",
                        mime: "image/jpeg",
                        name: "small_64.jpg",
                        path: null,
                        size: 24.41,
                        width: 500,
                        height: 281,
                        provider_metadata: {
                          public_id: "small_64_d25fe38464",
                          resource_type: "image",
                        },
                      },
                      medium: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669020499/medium_64_d25fe38464.jpg",
                        hash: "medium_64_d25fe38464",
                        mime: "image/jpeg",
                        name: "medium_64.jpg",
                        path: null,
                        size: 44.97,
                        width: 750,
                        height: 422,
                        provider_metadata: {
                          public_id: "medium_64_d25fe38464",
                          resource_type: "image",
                        },
                      },
                      thumbnail: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669020498/thumbnail_64_d25fe38464.jpg",
                        hash: "thumbnail_64_d25fe38464",
                        mime: "image/jpeg",
                        name: "thumbnail_64.jpg",
                        path: null,
                        size: 8.32,
                        width: 245,
                        height: 138,
                        provider_metadata: {
                          public_id: "thumbnail_64_d25fe38464",
                          resource_type: "image",
                        },
                      },
                    },
                    hash: "64_d25fe38464",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    size: 60.79,
                    url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669020498/64_d25fe38464.jpg",
                    previewUrl: null,
                    provider: "cloudinary",
                    provider_metadata: {
                      public_id: "64_d25fe38464",
                      resource_type: "image",
                    },
                    createdAt: "2022-11-21T08:48:20.703Z",
                    updatedAt: "2022-11-21T08:48:20.703Z",
                  },
                },
              },
              categories: {
                data: [
                  {
                    id: 4,
                    attributes: {
                      name: "Био продукти - biopedia",
                      slug: "bio-produkti",
                      createdAt: "2022-05-13T10:58:48.140Z",
                      updatedAt: "2022-07-23T14:24:53.496Z",
                      publishedAt: "2022-05-13T10:58:48.970Z",
                      bottomText: null,
                    },
                  },
                  {
                    id: 6,
                    attributes: {
                      name: "Био храни - biopedia",
                      slug: "bio-hrani",
                      createdAt: "2022-05-13T10:59:35.098Z",
                      updatedAt: "2022-07-23T14:25:10.806Z",
                      publishedAt: "2022-05-13T10:59:35.818Z",
                      bottomText: null,
                    },
                  },
                ],
              },
            },
          },
          {
            id: 744,
            attributes: {
              createdAt: "2022-11-21T08:27:02.939Z",
              title: "8 билки за намаляване на кортизола",
              description:
                "Ако искате да разберете кои са осемте билки, с който можете да намалите кортизола, прочетете тази статия.",
              slug: "8-bilki-za-namalyavane-na-kortizola",
              exclusive: null,
              image: {
                data: {
                  id: 3252,
                  attributes: {
                    name: "62.jpg",
                    alternativeText: "62.jpg",
                    caption: "62.jpg",
                    width: 912,
                    height: 513,
                    formats: {
                      small: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669021776/small_62_10b3e2bb38.jpg",
                        hash: "small_62_10b3e2bb38",
                        mime: "image/jpeg",
                        name: "small_62.jpg",
                        path: null,
                        size: 43.82,
                        width: 500,
                        height: 281,
                        provider_metadata: {
                          public_id: "small_62_10b3e2bb38",
                          resource_type: "image",
                        },
                      },
                      medium: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669021775/medium_62_10b3e2bb38.jpg",
                        hash: "medium_62_10b3e2bb38",
                        mime: "image/jpeg",
                        name: "medium_62.jpg",
                        path: null,
                        size: 83.88,
                        width: 750,
                        height: 422,
                        provider_metadata: {
                          public_id: "medium_62_10b3e2bb38",
                          resource_type: "image",
                        },
                      },
                      thumbnail: {
                        ext: ".jpg",
                        url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669021774/thumbnail_62_10b3e2bb38.jpg",
                        hash: "thumbnail_62_10b3e2bb38",
                        mime: "image/jpeg",
                        name: "thumbnail_62.jpg",
                        path: null,
                        size: 13.11,
                        width: 245,
                        height: 138,
                        provider_metadata: {
                          public_id: "thumbnail_62_10b3e2bb38",
                          resource_type: "image",
                        },
                      },
                    },
                    hash: "62_10b3e2bb38",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    size: 117.64,
                    url: "https://res.cloudinary.com/dyehjglkn/image/upload/v1669021773/62_10b3e2bb38.jpg",
                    previewUrl: null,
                    provider: "cloudinary",
                    provider_metadata: {
                      public_id: "62_10b3e2bb38",
                      resource_type: "image",
                    },
                    createdAt: "2022-11-21T09:09:36.714Z",
                    updatedAt: "2022-11-21T09:09:36.714Z",
                  },
                },
              },
              categories: {
                data: [
                  {
                    id: 4,
                    attributes: {
                      name: "Био продукти - biopedia",
                      slug: "bio-produkti",
                      createdAt: "2022-05-13T10:58:48.140Z",
                      updatedAt: "2022-07-23T14:24:53.496Z",
                      publishedAt: "2022-05-13T10:58:48.970Z",
                      bottomText: null,
                    },
                  },
                ],
              },
            },
          },
        ],
        meta: {
          pagination: { page: 1, pageSize: 9, pageCount: 12, total: 101 },
        },
      },
    },
    __N_SSG: true,
  },
  page: "/latest/[slug]",
  query: { slug: "0" },
  buildId: "LDTr81dlISJKbSnuHkvjo",
  isFallback: false,
  gsp: true,
  appGip: true,
  locale: "bg",
  locales: ["bg"],
  defaultLocale: "bg",
  scriptLoader: [],
}
